<a href="https://colab.research.google.com/github/kimkihyun1/TIL/blob/main/%EB%88%84%EB%9D%BD%EB%8D%B0%EC%9D%B4%ED%84%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 시리즈 만들기
import pandas as pd

dict_data = {'a': 1, 'b': 2, 'c': 3}
sr = pd.Series(dict_data)
print(sr)

a    1
b    2
c    3
dtype: int64


In [ ]:
# 시리즈 크기 확인
print(sr.shape)

(3,)


In [ ]:
# 인덱스 확인
print(sr.index)
print()

# 값 확인
print(sr.values)

Index(['a', 'b', 'c'], dtype='object')

[1 2 3]


In [ ]:
list_data = ['a', 'b', 'c', 'd']
sr = pd.Series(list_data)
print(sr)

0    a
1    b
2    c
3    d
dtype: object


In [ ]:
# 시리즈 만들기
import pandas as pd

dict_data = {'a': 1, 'b': 2, 'c': 3}
sr = pd.Series(dict_data)
print(sr[0])
print(sr['a'])

1
1


In [ ]:
print(sr[[0, 2]])
print(sr[['a', 'c']])

a    1
c    3
dtype: int64
a    1
c    3
dtype: int64


In [ ]:
print(sr[1:3])
print(sr['b':'c'])

b    2
c    3
dtype: int64
b    2
c    3
dtype: int64


In [ ]:
dict_data = {'c0': [1, 2, 3], 'c1': [2, 3, 4], 'c2': [3, 4, 5]}
df = pd.DataFrame(dict_data)
print(df)

   c0  c1  c2
0   1   2   3
1   2   3   4
2   3   4   5


In [ ]:
df = pd.DataFrame([['22', '남', 'cccr'], [32, '여', 'cloud']], index = ['학생1', '학생2'], columns = ['나이', '성별', '반이름'])
print(df)

     나이 성별    반이름
학생1  22  남   cccr
학생2  32  여  cloud


In [ ]:
dict_data = {'이름' : ['오규석', '임장근', '염찬영'],
             '국어': [90, 95, 100],
             '수학': [80, 90, 85],
             '영어': [95, 85, 90]}

df = pd.DataFrame(dict_data)
print(df)

    이름   국어  수학  영어
0  오규석   90  80  95
1  임장근   95  90  85
2  염찬영  100  85  90


In [ ]:
df2 = df.set_index('이름')
print(df2)

      국어  수학  영어
이름              
오규석   90  80  95
임장근   95  90  85
염찬영  100  85  90


In [ ]:
print(df2.loc['임장근', '국어'])

95


In [ ]:
print(df2.iloc[1, 0])

95


In [ ]:
print(df2.loc[['오규석', '염찬영'], ['국어', '영어']])

      국어  영어
이름          
오규석   90  95
염찬영  100  90


In [ ]:
print(df2.iloc[[0, 2], [0, 2]])

      국어  영어
이름          
오규석   90  95
염찬영  100  90


In [ ]:
print(df2.loc['임장근':'염찬영', '국어':'수학'])

      국어  수학
이름          
임장근   95  90
염찬영  100  85


In [ ]:
print(df2.iloc[1:3, 0:2])

      국어  수학
이름          
임장근   95  90
염찬영  100  85


In [ ]:
import seaborn as sns

df = sns.load_dataset('titanic')
print(df.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  


In [ ]:
print(df.deck)

0      NaN
1        C
2      NaN
3        C
4      NaN
      ... 
886    NaN
887      B
888    NaN
889      C
890    NaN
Name: deck, Length: 891, dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']


In [ ]:
print(df.deck.value_counts(dropna=False)) # False로 지정해야 NaN 값을 확인할 수 있다

NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: deck, dtype: int64


In [ ]:
print(df.deck.isnull()) # null 이면 참

0       True
1      False
2       True
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Name: deck, Length: 891, dtype: bool


In [ ]:
print(df.deck.notnull()) # null이 아니면 참

0      False
1       True
2      False
3       True
4      False
       ...  
886    False
887     True
888    False
889     True
890    False
Name: deck, Length: 891, dtype: bool


In [ ]:
print(df.deck.isnull().sum()) # NaN 값의 개수

688


In [ ]:
import seaborn as sns

df = sns.load_dataset('titanic')

missing_data = df.isnull()
print(missing_data)

     survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0       False   False  False  False  False  False  False     False  False   
1       False   False  False  False  False  False  False     False  False   
2       False   False  False  False  False  False  False     False  False   
3       False   False  False  False  False  False  False     False  False   
4       False   False  False  False  False  False  False     False  False   
..        ...     ...    ...    ...    ...    ...    ...       ...    ...   
886     False   False  False  False  False  False  False     False  False   
887     False   False  False  False  False  False  False     False  False   
888     False   False  False   True  False  False  False     False  False   
889     False   False  False  False  False  False  False     False  False   
890     False   False  False  False  False  False  False     False  False   

       who  adult_male   deck  embark_town  alive  alone  
0    False      

In [ ]:
print(missing_data.columns)
print(type(missing_data.columns))

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')
<class 'pandas.core.indexes.base.Index'>


In [ ]:
for col in missing_data.columns:
    missing_count = missing_data[col].value_counts()

    try:
        print(col, ':', missing_count[True])
    except:
        print(col, ':', 0)

survived : 0
pclass : 0
sex : 0
age : 177
sibsp : 0
parch : 0
fare : 0
embarked : 2
class : 0
who : 0
adult_male : 0
deck : 688
embark_town : 2
alive : 0
alone : 0


In [ ]:
df_drop = df.dropna(axis=1) # 행은 axis=0, 열은 axis=1
print(df_drop)

     survived  pclass     sex  sibsp  parch     fare   class    who  \
0           0       3    male      1      0   7.2500   Third    man   
1           1       1  female      1      0  71.2833   First  woman   
2           1       3  female      0      0   7.9250   Third  woman   
3           1       1  female      1      0  53.1000   First  woman   
4           0       3    male      0      0   8.0500   Third    man   
..        ...     ...     ...    ...    ...      ...     ...    ...   
886         0       2    male      0      0  13.0000  Second    man   
887         1       1  female      0      0  30.0000   First  woman   
888         0       3  female      1      2  23.4500   Third  woman   
889         1       1    male      0      0  30.0000   First    man   
890         0       3    male      0      0   7.7500   Third    man   

     adult_male alive  alone  
0          True    no  False  
1         False   yes  False  
2         False   yes   True  
3         False   yes  

In [ ]:
df_thresh = df.dropna(axis=1, thresh=500)  # NaN값이 500개 이상이면 제거
print(df_thresh)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male  embark_town alive  alone  


In [ ]:
df_age = df.dropna(subset=['age'], how='any') # subset은 특정 열을 선택할수 있다, how='all'은 행의 전체가 NaN 일때만 제거, how='any'은 행의 일부가 NaN이 있을 때 제거
print(df_age)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
885         0       3  female  39.0      0      5  29.1250        Q   Third   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alo

In [ ]:
# 평균값 대체
import seaborn as sns

df = sns.load_dataset('titanic')
mean_age = df['age'].mean()
print(mean_age)

29.69911764705882


In [ ]:
df['age'].fillna(mean_age, inplace=True)
print(df.iloc[10:25]) # 17행의 age 값이 NaN에서 mean_age값으로 대체

    survived  pclass     sex        age  sibsp  parch     fare embarked  \
10         1       3  female   4.000000      1      1  16.7000        S   
11         1       1  female  58.000000      0      0  26.5500        S   
12         0       3    male  20.000000      0      0   8.0500        S   
13         0       3    male  39.000000      1      5  31.2750        S   
14         0       3  female  14.000000      0      0   7.8542        S   
15         1       2  female  55.000000      0      0  16.0000        S   
16         0       3    male   2.000000      4      1  29.1250        Q   
17         1       2    male  29.699118      0      0  13.0000        S   
18         0       3  female  31.000000      1      0  18.0000        S   
19         1       3  female  29.699118      0      0   7.2250        C   
20         0       2    male  35.000000      0      0  26.0000        S   
21         1       2    male  34.000000      0      0  13.0000        S   
22         1       3  fem

In [ ]:
# 최빈값 대체
import seaborn as sns

df = sns.load_dataset('titanic')
print(df.embark_town[825:830])

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829            NaN
Name: embark_town, dtype: object


In [ ]:
most_freq = df.embark_town.value_counts(dropna=True).idxmax()
print(most_freq)

Southampton


In [ ]:
df.embark_town.fillna(most_freq, inplace=True)
print(df.embark_town[825:830])

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829    Southampton
Name: embark_town, dtype: object


In [ ]:
df = pd.DataFrame({'A': [1, '-', 3],
                   'B': ['-', 5, '-'],
                   'C': [7, 8, '-']})
print(df)

   A  B  C
0  1  -  7
1  -  5  8
2  3  -  -


In [ ]:
import numpy as np

df.replace('-', np.nan, inplace=True)
print(df)

     A    B    C
0  1.0  NaN  7.0
1  NaN  5.0  8.0
2  3.0  NaN  NaN


In [ ]:
# NaN값을 바로 위,아래 데이터로 대체
import seaborn as sns

df = sns.load_dataset('titanic')
print(df.embark_town[825:835])

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829            NaN
830      Cherbourg
831    Southampton
832      Cherbourg
833    Southampton
834    Southampton
Name: embark_town, dtype: object


In [ ]:
df.embark_town.fillna(method='ffill', inplace=True) # 위 데이터로 대체
print(df.embark_town[825:835])

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829     Queenstown
830      Cherbourg
831    Southampton
832      Cherbourg
833    Southampton
834    Southampton
Name: embark_town, dtype: object


In [ ]:
import seaborn as sns

df = sns.load_dataset('titanic')
print(df.embark_town[825:835])
print()

df.embark_town.fillna(method='bfill', inplace=True) # 아래 데이터로 대체
print(df.embark_town[825:835])

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829            NaN
830      Cherbourg
831    Southampton
832      Cherbourg
833    Southampton
834    Southampton
Name: embark_town, dtype: object

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829      Cherbourg
830      Cherbourg
831    Southampton
832      Cherbourg
833    Southampton
834    Southampton
Name: embark_town, dtype: object


In [ ]:
# 중복 데이터 처리
df = pd.DataFrame({'c1' : ['a', 'b', 'a', 'a', 'b'],
                   'c2': [1, 1, 1, 2, 2],
                   'c3': [1, 1, 1, 2, 2]})
print(df)

  c1  c2  c3
0  a   1   1
1  b   1   1
2  a   1   1
3  a   2   2
4  b   2   2


In [ ]:
df_dup = df.duplicated()
print(df_dup)

0    False
1    False
2     True
3    False
4    False
dtype: bool


In [ ]:
col_dup = df['c2'].duplicated()
print(col_dup)

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool


In [ ]:
df = pd.DataFrame({'c1' : ['a', 'b', 'a', 'a', 'b'],
                   'c2': [1, 1, 1, 2, 2],
                   'c3': [1, 1, 1, 2, 2]})
print(df)
print()
df2 = df.drop_duplicates()
print(df2)

  c1  c2  c3
0  a   1   1
1  b   1   1
2  a   1   1
3  a   2   2
4  b   2   2

  c1  c2  c3
0  a   1   1
1  b   1   1
3  a   2   2
4  b   2   2


In [ ]:
df3 = df.drop_duplicates(subset=['c2', 'c3'])
print(df3)

  c1  c2  c3
0  a   1   1
3  a   2   2


In [ ]:
import pandas as pd

df = pd.read_excel('/content/auto-mpg.xlsx')
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower',
              'weight', 'acceleration', 'model_year', 'origin', 'name']
print(df.head())


    mpg  cylinders  displacement horsepower  weight  acceleration  model_year  \
0  15.0          8         350.0        165    3693          11.5          70   
1  18.0          8         318.0        150    3436          11.0          70   
2  16.0          8         304.0        150    3433          12.0          70   
3  17.0          8         302.0        140    3449          10.5          70   
4  15.0          8         429.0        198    4341          10.0          70   

   origin                name  
0       1   buick skylark 320  
1       1  plymouth satellite  
2       1       amc rebel sst  
3       1         ford torino  
4       1    ford galaxie 500  


In [ ]:
mpg_to_kpl = 1.60934 / 3.78541
df['kpl'] = mpg_to_kpl * df['mpg']
print(df.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model_year  \
0  15.0          8         350.0        165    3693          11.5          70   
1  18.0          8         318.0        150    3436          11.0          70   
2  16.0          8         304.0        150    3433          12.0          70   
3  17.0          8         302.0        140    3449          10.5          70   
4  15.0          8         429.0        198    4341          10.0          70   

   origin                name       kpl  
0       1   buick skylark 320  6.377143  
1       1  plymouth satellite  7.652571  
2       1       amc rebel sst  6.802286  
3       1         ford torino  7.227428  
4       1    ford galaxie 500  6.377143  


In [ ]:
df['kpl'] = df['kpl'].round(2)
print(df.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model_year  \
0  15.0          8         350.0        165    3693          11.5          70   
1  18.0          8         318.0        150    3436          11.0          70   
2  16.0          8         304.0        150    3433          12.0          70   
3  17.0          8         302.0        140    3449          10.5          70   
4  15.0          8         429.0        198    4341          10.0          70   

   origin                name   kpl  
0       1   buick skylark 320  6.38  
1       1  plymouth satellite  7.65  
2       1       amc rebel sst  6.80  
3       1         ford torino  7.23  
4       1    ford galaxie 500  6.38  


In [ ]:
import pandas as pd

df = pd.read_excel('/content/auto-mpg.xlsx')
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower',
              'weight', 'acceleration', 'model_year', 'origin', 'name']

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model_year        int64
origin            int64
name             object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           397 non-null    float64
 1   cylinders     397 non-null    int64  
 2   displacement  397 non-null    float64
 3   horsepower    397 non-null    object 
 4   weight        397 non-null    int64  
 5   acceleration  397 non-null    float64
 6   model_year    397 non-null    int64  
 7   origin        397 non-null    int64  
 8   name          397 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.0+ KB


In [ ]:
df.horsepower.unique()

array([165, 150, 140, 198, 220, 215, 225, 190, 170, 160, 95, 97, 85, 88,
       46, 87, 90, 113, 200, 210, 193, '?', 100, 105, 175, 153, 180, 110,
       72, 86, 70, 76, 65, 69, 60, 80, 54, 208, 155, 130, 112, 92, 145,
       137, 158, 167, 94, 107, 230, 49, 75, 91, 122, 67, 83, 78, 52, 61,
       93, 148, 129, 96, 71, 98, 115, 53, 81, 79, 120, 152, 102, 108, 68,
       58, 149, 89, 63, 48, 66, 139, 103, 125, 133, 138, 135, 142, 77, 62,
       132, 84, 64, 74, 116, 82], dtype=object)

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_excel('/content/auto-mpg.xlsx')
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower',
              'weight', 'acceleration', 'model_year', 'origin', 'name']

print(type(np.nan))

<class 'float'>


In [ ]:
df.horsepower.replace('?', np.nan, inplace=True)
df.horsepower.isnull().sum()

6

In [ ]:
df.dropna(subset=['horsepower'], inplace=True)
df['horsepower'].isnull().sum()

0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 391 entries, 0 to 396
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           391 non-null    float64
 1   cylinders     391 non-null    int64  
 2   displacement  391 non-null    float64
 3   horsepower    391 non-null    float64
 4   weight        391 non-null    int64  
 5   acceleration  391 non-null    float64
 6   model_year    391 non-null    int64  
 7   origin        391 non-null    int64  
 8   name          391 non-null    object 
dtypes: float64(4), int64(4), object(1)
memory usage: 30.5+ KB


In [ ]:
df.origin.replace({1: 'USA', 2: 'EU', 3: 'JAPAN'}, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 391 entries, 0 to 396
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           391 non-null    float64
 1   cylinders     391 non-null    int64  
 2   displacement  391 non-null    float64
 3   horsepower    391 non-null    float64
 4   weight        391 non-null    int64  
 5   acceleration  391 non-null    float64
 6   model_year    391 non-null    int64  
 7   origin        391 non-null    object 
 8   name          391 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 30.5+ KB


In [ ]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  15.0          8         350.0       165.0    3693          11.5   
1  18.0          8         318.0       150.0    3436          11.0   
2  16.0          8         304.0       150.0    3433          12.0   
3  17.0          8         302.0       140.0    3449          10.5   
4  15.0          8         429.0       198.0    4341          10.0   

   model_year origin                name  
0          70    USA   buick skylark 320  
1          70    USA  plymouth satellite  
2          70    USA       amc rebel sst  
3          70    USA         ford torino  
4          70    USA    ford galaxie 500

In [ ]:
df.origin = df.origin.astype('category')  # 범주형 데이터 타입
print(df.origin.dtypes)

category


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 391 entries, 0 to 396
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   mpg           391 non-null    float64 
 1   cylinders     391 non-null    int64   
 2   displacement  391 non-null    float64 
 3   horsepower    391 non-null    float64 
 4   weight        391 non-null    int64   
 5   acceleration  391 non-null    float64 
 6   model_year    391 non-null    int64   
 7   origin        391 non-null    category
 8   name          391 non-null    object  
dtypes: category(1), float64(4), int64(3), object(1)
memory usage: 28.0+ KB


In [ ]:
df.model_year = df.model_year.astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 391 entries, 0 to 396
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   mpg           391 non-null    float64 
 1   cylinders     391 non-null    int64   
 2   displacement  391 non-null    float64 
 3   horsepower    391 non-null    float64 
 4   weight        391 non-null    int64   
 5   acceleration  391 non-null    float64 
 6   model_year    391 non-null    category
 7   origin        391 non-null    category
 8   name          391 non-null    object  
dtypes: category(2), float64(4), int64(2), object(1)
memory usage: 26.0+ KB


In [ ]:
df.model_year.sample(5)

178    75
354    81
309    80
192    76
202    76
Name: model_year, dtype: category
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]

In [ ]:
df = pd.read_excel('/content/auto-mpg.xlsx')

df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower',
              'weight', 'acceleration', 'model_year', 'origin', 'name']


df['horsepower'].replace('?', np.nan, inplace = True)
df.dropna(subset = ['horsepower'], inplace = True)
df['horsepower'] = df['horsepower'].astype('float')

count, bin_dividers = np.histogram(df.horsepower, bins=3)
print(count) # 저출력 중간출력 고출력
print()
print(bin_dividers) # 경계값

[257 102  32]

[ 46.         107.33333333 168.66666667 230.        ]


In [ ]:
bin_names = ['저출력', '중간출력', '고출력']
df['hp_bin'] = pd.cut(x=df.horsepower,
                   bins=bin_dividers,
                   labels=bin_names,
                   include_lowest=True)

print(df.head(10))

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  15.0          8         350.0       165.0    3693          11.5   
1  18.0          8         318.0       150.0    3436          11.0   
2  16.0          8         304.0       150.0    3433          12.0   
3  17.0          8         302.0       140.0    3449          10.5   
4  15.0          8         429.0       198.0    4341          10.0   
5  14.0          8         454.0       220.0    4354           9.0   
6  14.0          8         440.0       215.0    4312           8.5   
7  14.0          8         455.0       225.0    4425          10.0   
8  15.0          8         390.0       190.0    3850           8.5   
9  15.0          8         383.0       170.0    3563          10.0   

   model_year  origin                 name hp_bin  
0          70       1    buick skylark 320   중간출력  
1          70       1   plymouth satellite   중간출력  
2          70       1        amc rebel sst   중간출력  
3          70       1

In [ ]:
horsepower_dummies = pd.get_dummies(df['hp_bin'])
print(horsepower_dummies)

     저출력  중간출력  고출력
0      0     1    0
1      0     1    0
2      0     1    0
3      0     1    0
4      0     0    1
..   ...   ...  ...
392    1     0    0
393    1     0    0
394    1     0    0
395    1     0    0
396    1     0    0

[391 rows x 3 columns]


In [ ]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

onehot_labeled = label_encoder.fit_transform(df['hp_bin'].head(15))
print(onehot_labeled)

[2 2 2 2 0 0 0 0 0 0 2 2 0 1 1]


In [ ]:
onehot_reshaped = onehot_labeled.reshape(len(onehot_labeled), 1)
print(onehot_reshaped)

[[2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [2]
 [2]
 [0]
 [1]
 [1]]


In [ ]:
onehot_fitted = onehot_encoder.fit_transform(onehot_reshaped)
print(onehot_fitted)

  (0, 2)	1.0
  (1, 2)	1.0
  (2, 2)	1.0
  (3, 2)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 2)	1.0
  (11, 2)	1.0
  (12, 0)	1.0
  (13, 1)	1.0
  (14, 1)	1.0
